### ISSUE TITLE
Try to change values of element selected item of Listview ,but changed value of that element in whole list?

### ISSUE THREAD

**Issue by Sandeep145XamRN** [sourabhsoni/XamGroup#1]
**Xaml code**

<controls:ExtendedListView                 
                 ItemTemplate="{StaticResource CellSelector}" 
                 ItemsSource="{Binding ListItems}"                
                 HasUnevenRows="True" SelectionMode="Single" SelectedItem="{Binding ItemTappedCommand}"                 
                 VerticalOptions="FillAndExpand" 
                 SeparatorColor="Transparent">
                <x:Arguments>
                    <ListViewCachingStrategy>RecycleElement</ListViewCachingStrategy>
                </x:Arguments>
         </controls:ExtendedListView>

**ViewModel code**

public class AbsenceViewModel:BaseNotifyPropertyChanged
    {
        
        private List<AbsenceModel> _listItems;
        public List<AbsenceModel>  ListItems
        {
            get { return _listItems; }
            set
            {
                _listItems = value;
                OnPropertyChanged("ListItems");
            }
        }
        private AbsenceModel _itemTappedCommand;
        public AbsenceModel ItemTappedCommand
        {
            get { return _itemTappedCommand; }
            set
            {
                _itemTappedCommand = value;
                if (_itemTappedCommand != null)
                {
                    SelectionExecute(_itemTappedCommand);
                    OnPropertyChanged("ItemTappedCommand");
                }
            }
        }
      
        public AbsenceViewModel()
        {
            ListItems = new List<AbsenceModel>();            
            var cellItem = new AbsenceModel()
            {
                CheckIn="8:40 am",
                Checkout="12:30 pm"
            };
            for (int i = 0; i <= 10; i++)
            {
                ListItems.Add(cellItem);
            }
           
        }
       
        private void SelectionExecute(AbsenceModel arg)
        {           
            arg.Clicked = "Selected";        
            foreach (var item in ListItems)
            {
                if (item.Clicked == "Selected")
                {
                    item.IsExpand = !item.IsExpand;
                    item.Clicked = string.Empty;
                }                    
            }
        }
    }

**Model class**

public class AbsenceModel:BaseNotifyPropertyChanged
    {
        private bool _isCorrected;
        public bool IsCorrected
        {
            get { return _isCorrected; }
            set
            {
                _isCorrected = value;
                OnPropertyChanged("IsCorrected");
            }
        }
        private string _date;
        public string Date
        {
            get { return _date; }
            set
            {
                _date = value;
                OnPropertyChanged("Date");
            }
        }
        private string _checkIn;
        public string CheckIn
        {
            get { return _checkIn; }
            set
            {
                _checkIn = value;
                OnPropertyChanged("CheckIn");
            }
        }
        private string _checkout;
        public string Checkout
        {
            get { return _checkout; }
            set
            {
                _checkout = value;
                OnPropertyChanged("Checkout");
            }
        }
        private string _apply;
        public string Apply
        {
            get { return _apply; }
            set
            {
                _apply = value;
                OnPropertyChanged("Apply");
            }
        }
        private bool _isExpand;
        public bool IsExpand
        {
            get { return _isExpand; }
            set
            {
                _isExpand = value;
                OnPropertyChanged("IsExpand");
            }
        }
        
        public ICommand ExpandCommand
        {
            get
            {
                return new Command((e) =>
                {
                    var item = (e as AbsenceModel);
                    // delete logic on item
                });
            }
        }
        private string _clicked;
        public string Clicked
        {
            get { return _clicked; }
            set
            {
                _clicked = value;
                OnPropertyChanged("Clicked");
            }
        }
    }

**Comment by sourabhsoni** [comment]
Take the latest code from repository. Its resolved.

issue was here
 public AbsenceViewModel()
        {
            ListItems = new List<AbsenceModel>();
            //var cellItem = new AbsenceModel()
            //{
            //    CheckIn = "8:40 am",
            //    Checkout = "12:30 pm"
            //};
            for (int i = 0; i <= 10; i++)
            {
                ListItems.Add(new AbsenceModel()
                {
                    CheckIn = "8:40 am",
                    Checkout = "12:30 pm"
                });
            }

        }

Make changes here as well
 private void SelectionExecute(AbsenceModel arg)
        {
            arg.Clicked = "Selected";
            foreach (var item in ListItems)
            {
                if (item.Clicked == "Selected")
                {
                    item.IsExpand = !item.IsExpand;
                    item.Clicked = string.Empty;
                }
                else
                {
                    item.Clicked = string.Empty;
                }
            }
        }

**Comment by Sandeep145XamRN** [comment]
> Take the latest code from repository. Its resolved.
> 
> issue was here
> public AbsenceViewModel()
> {
> ListItems = new List();
> //var cellItem = new AbsenceModel()
> //{
> // CheckIn = "8:40 am",
> // Checkout = "12:30 pm"
> //};
> for (int i = 0; i <= 10; i++)
> {
> ListItems.Add(new AbsenceModel()
> {
> CheckIn = "8:40 am",
> Checkout = "12:30 pm"
> });
> }
> 
> ```
>     }
> ```
> 
> Make changes here as well
> private void SelectionExecute(AbsenceModel arg)
> {
> arg.Clicked = "Selected";
> foreach (var item in ListItems)
> {
> if (item.Clicked == "Selected")
> {
> item.IsExpand = !item.IsExpand;
> item.Clicked = string.Empty;
> }
> else
> {
> item.Clicked = string.Empty;
> }
> }
> }

@sourabhsoni  Works fine 👍 ,thanks a lot.
